### ISSUE TITLE
online documentation displaying missing attribute status

### ISSUE THREAD

**Issue by abalam666** [googleapis/nodejs-video-transcoder#136]
Hello,

This documentation https://cloud.google.com/transcoder/docs/how-to/migrate-to-v1#v1 is showing an attribute `"status":"PERMISSION_DENIED",`

```
{
  "name": "projects/PROJECT_NUMBER/locations/LOCATION/jobs/JOB_ID",
  ...
  "state": "FAILED",
  "error": {
    "code":403,
    "message":"Permission denied for Google Cloud Storage.",
    "status":"PERMISSION_DENIED",
    "details":[
      {
        "@type":"type.googleapis.com/google.rpc.ErrorInfo",
        "reason":"GCSPermissionDenied",
        "domain":"transcoder.googleapis.com",
        "metadata":{
          "details":"my_sa@my_project.iam.gserviceaccount.com does not
            have storage.objects.get access to gs://example/input/video.mp4."
        }
      }
    ]
  }
}
```

But typescript raise errors on `protos.google.cloud.video.transcoder.v1.IJob` type because this attribute `status` does not exists in interfaces/classes provided here :
https://github.com/googleapis/nodejs-video-transcoder/blob/1a89a21328feece1d67bdd1f16c8beacc3acea58/protos/protos.d.ts#L15060

Is it a mistake in documentation or in typescript source ?

Thank you for your help !

**Comment by chingor13** [comment]
The credentials you are using appear to not have permissions to the source video file. Be sure to grant the appropriate access to your service account.

**Comment by abalam666** [comment]
?

**Comment by abalam666** [comment]
Are you kidding me?
Maybe be you didn't did you read right the question?

I don't experience any error trggered.

I'm unit testing and find that the source code provided by Github isn't showing the same structure documented in the official documentation.

**Comment by abalam666** [comment]
![image](https://user-images.githubusercontent.com/1979302/147132921-583db605-8d23-45cc-ad40-bbd27936aff7.png)

![image](https://user-images.githubusercontent.com/1979302/147132985-7e5a0fa2-9828-4b47-9adc-fee241ebd3bd.png)

is it better then words ?

**Comment by irataxy** [comment]
This is indeed a documentation issue. It should be fixed now: https://cloud.google.com/transcoder/docs/how-to/migrate-to-v1

Thanks for bringing this to our attention.

**Comment by abalam666** [comment]
You're welcome.
Thanks to you.
