### ISSUE TITLE
Probing Feature

### ISSUE THREAD

**Issue by tommyc38** [googleapis/nodejs-video-transcoder#35]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
My transcoding inputs and UI depend on Metadata for videos, specifically resolution.
 **Describe the solution you'd like**
I would like to be able to get metadata from a video so I can use that info to processes the video.
 **Describe alternatives you've considered**
An alternative would be to use GAE to download my video and then use FFMPEG to probe for metadata, then use that data to make a job request.  
 **Additional context**

**Comment by sofisl** [comment]
Hi there! I think this would be better logged against the [API itself](https://issuetracker.google.com/savedsearches/5084810). Thank you!
