### ISSUE TITLE
Client returning `Internal error encountered`

### ISSUE THREAD

**Issue by deep-randhawa** [googleapis/nodejs-video-transcoder#65]
- OS: macOS
  - Node.js version: v.16.1.0
  - npm version: 7.11.2
  - `@google-cloud/video-transcoder` version:  1.4.1

#### Steps to reproduce

  1. Create a job with the following `config` object:
  ```
{
    parent: "projects/xxx/locations/us-central1",
    job: {
        inputUri: gs://xxx.appspot.com/kejMkh7oYwbbQGTYnZUNZ6QA8Vou/original.mov,
        outputUri: gs://xxx.appspot.com/kejMkh7oYwbbQGTYnZUNZ6QA8Vou/,
        config: {
            elementaryStreams: [
                {
                    key: video-stream0,
                    videoStream: {
                        codec: h265,
                        heightPixels: 1080,
                        widthPixels: 1920,
                        bitrateBps: 7651584,
                        frameRate: 30
                    }
                },
                {
                    key: audio-stream0,
                    audioStream: {
                        codec: aac,
                        bitrateBps: 96000,
                        channelCount: 1,
                        sampleRateHertz: 44100
                    }
                }
            ],
            muxStreams: [
                {
                    key: sd,
                    container: mp4,
                    elementaryStreams: [
                        video-stream0,
                        audio-stream0
                    ]
                }
            ],
            spriteSheets: [
                {
                    filePrefix: small-sprite-sheet,
                    spriteHeightPixels: 32,
                    spriteWidthPixels: 64,
                    totalCount: 5
                },
                {
                    filePrefix: large-sprite-sheet,
                    spriteHeightPixels: 72,
                    spriteWidthPixels: 128,
                    totalCount: 5
                }
            ]
        }
    }
}
  ```
 
Received the following error from client:
```
13 INTERNAL: Internal error encountered.
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sofisl** [comment]
I'm curious if the issue is something simple. Would you mind replacing the parent field with this:

```
      parent: transcoderServiceClient.locationPath(projectId, location)
```

And generally comparing against [this sample](https://github.com/googleapis/nodejs-video-transcoder/blob/master/samples/createJobFromAdHoc.js).

If it doesn't work, I'll attempt to reproduce the issue more completely.

**Comment by deep-randhawa** [comment]
hi @sofisl , thanks for replying. Actually in code the `parent` line is exactly what you recommended. I just pasted to resolved JSON payload here. 

Please let me know if there is any other information I can provide to make it easier for you to debug. For reference, this is the asset I was testing with.

https://user-images.githubusercontent.com/5448275/119421025-967e6b00-bcb2-11eb-8d03-74b4593feaa5.mov

**Comment by sofisl** [comment]
Hi @deep-randhawa, thanks so much for the video! It helped with the debugging.

I think this seems to be an issue at the bit level. The `bitrateBps` field seems to only take numbers divisible by 10, i.e., `7651590` or `7651580`. Can you give that a try and see if it works for you?

**Comment by deep-randhawa** [comment]
@sofisl that totally worked. Thank YOU :)
