### ISSUE TITLE
Generated manifest is missing paths to video files.

### ISSUE THREAD

**Issue by dackers86** [googleapis/nodejs-video-transcoder#80]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
I believe this could either a client or product issue at this stage.

2) Did someone already solve this?
 N/a

3) Do you have a support contract?
No.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: N/a (Firebase Extension Platform)
  - Node.js version: nodejs10
  - npm version: 7.11.2
  - `@google-cloud/video-transcoder` version: ^1.3.0

#### Steps to reproduce

  1. Create a basic `CreateJobRequest` via template Id of 'preset/web-hd'
  
  ```js
  const jobRequest: ICreateJobRequest = {
    parent: videoTranscoderServiceClient.locationPath(
      config.projectId,
      config.location
    ),
    job: {
      inputUri: `gs://${object.bucket}/${object.name}`,
      outputUri,
      templateId,
    },
  };
  ```
  
  2. Create the Job request
  
  ```js
  await videoTranscoderServiceClient.createJob(jobRequest);
  ```

3. View the output files, this will be similar to...

![image](https://user-images.githubusercontent.com/2060661/124488347-a4420880-dda7-11eb-8217-d36f77c81af3.png)

4. Inspect the manifest, eg.

```
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=852064,AVERAGE-BANDWIDTH=731833,RESOLUTION=640x360,CODECS="avc1.64001e,mp4a.40.2"
media-sd.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3277870,AVERAGE-BANDWIDTH=2745108,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
media-hd.m3u8
```

This should contain references to the generated input files, in the example this would be the `mp4` files.

References https://github.com/GoogleCloudPlatform/firebase-extensions/issues/6

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by rlee1990** [comment]
Any update on this?

**Comment by irataxy** [comment]
The output files are referenced. To have the manifest contain references to the generated input files, please file a feature request at https://issuetracker.google.com/issues/new?component=1137559

See also https://cloud.google.com/transcoder/docs/concepts/overview#job_template for the list of output files for preset `preset/web-hd`.
