### ISSUE TITLE
1.5.0 expects at least one ElementaryStream in the config object, even for non ad-hoc cases

### ISSUE THREAD

**Issue by wilsontayar** [googleapis/nodejs-video-transcoder#90]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
Not sure, but probably client library, since the docs states these props as "optional". 
(ref: https://googleapis.dev/nodejs/transcoder/latest/google.cloud.video.transcoder.v1beta1.IJobConfig.html)

2) Did someone already solve this?
No issues or questions that I have found so far. Sorry if that's the case 😅

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: N/A (GCP Functions)
  - Node.js version: nodejs10
  - npm version: N/A (GCP Functions)
  - `@google-cloud/video-transcoder` version: 1.5.0

#### Steps to reproduce

  1. If you create a job request without a pubsubDestination (hence the config object), you should see everything running smoothly:
  ```javascript
  const request: {
  parent: transcoderServiceClient.locationPath(projectId,location),
  job: {
    inputUri: inputUri,
    outputUri: outputUri,
    templateId: 'preset/web-hd',
  },
};
```
  2. But, as soon as I try to use a pubsubDestination, it errors expecting an ElementaryStream
  ```javascript
const request: {
  parent: transcoderServiceClient.locationPath(projectId,location),
  job: {
    inputUri: inputUri,
    outputUri: outputUri,
    templateId: 'preset/web-hd',
    config: {
      pubsubDestination: {
        topic: `/projects/${projectId}/topics/${topicName}`
      }
    }
  },
};
```

```javascript
Error: 3 INVALID_ARGUMENT: Request field config.elementaryStreams is missing, expected at least one ElementaryStream.
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at process.nextTick (/workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by chingor13** [comment]
This error response is coming from the backend service. It seems like the value is marked as optional in the pure API definition but may actually required under certain circumstances. Unfortunately, those circumstances are not clearly documented.

Here's a link to the support page for the backend service: https://cloud.google.com/transcoder/docs/getting-support. The team that manages this repository only handle what's provided to us, so please forward this question to one of those support channels.

**Comment by wilsontayar** [comment]
Thanks for the clarification, @chingor13. Getting in touch with the support team right away.

**Comment by wilsontayar** [comment]
For anyone having the same problem, the support team clarified that:
>When you use a template_id to create a job, the Job.config is populated by the JobTemplate.config. That means when creating a job from a template, you cannot specify the config field 'pubsubDestination:' again.

So your options are [1] using ad-hoc jobs with 'pubsubDestination' in the config, or [2] create a job template with the pubsubDestination in the config of the template.

With that in mind, I don't think it's possible to have pubsub job updates by using the default 'preset/web-hd' anymore.
